/**
 * @file zstd_matchfinder.c
 *
 * Match finding for Zstandard encoder in the Ghoti.io Compress library.
 *
 * ## Algorithm Overview
 *
 * This implements a hash chain match finder for LZ77-style compression:
 * - Each position is hashed using a 4-byte (or 5-byte) hash
 * - Hash collisions form a chain (linked list via chain_table)
 * - To find matches, look up the hash and follow the chain
 * - Chain depth is tuned by compression level
 *
 * ## Data Structures
 *
 * - **hash_table[hash]**: Position+1 of the most recent occurrence of this hash
 *   (0 means no entry). Positions are stored as value+1 to distinguish from
 *   "no entry" (which would be position 0 for the first byte).
 *
 * - **chain_table[pos]**: Position+1 of the previous occurrence with same hash.
 *   Forms a linked list of candidates to check for matches.
 *
 * ## Compression Levels
 *
 * Higher levels search more chain entries for potentially longer matches:
 *
 * | Level | Search Depth | Speed  | Compression |
 * |-------|--------------|--------|-------------|
 * | 1     | 4            | Fast   | Low         |
 * | 2-3   | 16           | Fast   | Low-Medium  |
 * | 4-6   | 64           | Medium | Medium      |
 * | 7-12  | 256          | Slow   | High        |
 * | 13-22 | 512+         | Slow   | Highest     |
 *
 * ## Sequence Generation
 *
 * Sequences are generated by scanning input and finding matches:
 *
 * 1. At each position, try to find a match using the hash chain
 * 2. If a match is found:
 *    - Record literals since last match (literal_length)
 *    - Record match offset (distance back to match source)
 *    - Record match length
 *    - Advance past the match, inserting intermediate positions into hash
 * 3. If no match, advance by one byte
 * 4. After scanning, append remaining bytes as trailing literals
 *
 * ## Deferred ("Lazy") Matching
 *
 * Step 2 above, taken on its own, is a greedy parse: the first match found is
 * always the one emitted.  Greedy is not optimal, and the reason is easy to
 * state.  A match found at position p blocks every match that starts inside
 * it.  If the position one byte later begins a match that is long enough to
 * pay for the literal that reaching it costs, emitting the literal and taking
 * the later match encodes more of the input for the same number of bits.
 *
 * So before committing to a match, the finder searches the next position as
 * well and keeps whichever of the two is worth more.  It may do this more
 * than once -- `lazy_depth` says how many times -- walking forward one byte at
 * a time for as long as each step keeps improving.
 *
 * "Worth more" is decided by zstd_mf_match_gain(), which is a bit-cost model,
 * not a length comparison: a longer match reached through a more distant
 * offset can cost more bits than a shorter one close by, because the offset's
 * extra bits are written raw (RFC 8878 section 3.1.1.3.2.1.1).
 *
 * The search stops early once a match reaches `nice_length`, on the grounds
 * that a match that long will not plausibly be beaten by enough to justify
 * the search, and both knobs are zero/low at the fast levels where the point
 * of the level is to not do this.
 *
 * ## Repeat Offset Handling
 *
 * Zstd uses "repeat offsets" to efficiently encode common patterns:
 * - rep_offset_1, rep_offset_2, rep_offset_3 track recent offsets
 * - When a match uses the same offset as a recent one, encode it as 1, 2, or 3
 * - This saves bits compared to encoding the full offset
 *
 * Special case: When literal_length == 0 (adjacent matches), the repeat offset
 * codes are shifted. To avoid complexity, we don't use repeat offsets when
 * literal_length is 0.
 *
 * Reference: RFC 8878 (https://www.rfc-editor.org/rfc/rfc8878.html)
 *
 * Copyright 2026 by Corey Pennycuff
 */

#define _POSIX_C_SOURCE 200809L

#include <ghoti.io/compress/macros.h>
#include "../../core/endian.h"
#include "zstd_internal.h"
#include <string.h>

//
// Match Finder Constants
//

#define MF_MIN_MATCH 3           ///< Minimum match length
#define MF_HASH_READ_SIZE 4      ///< Bytes read by hash function (must be >= 4)
#define MF_HASH_LOG_DEFAULT 17   ///< Default hash table log (128K entries)
#define MF_HASH_LOG_MIN 12       ///< Minimum hash table log
#define MF_HASH_LOG_MAX 20       ///< Maximum hash table log
#define MF_CHAIN_LOG_DEFAULT 16  ///< Default chain table log (64K entries)
#define MF_MAX_DISTANCE 0x7FFFFF ///< Maximum match distance (~8MB for blocks)

//
// Hash Functions
//

/**
 * @brief Compute hash for 4 bytes.
 */
static inline uint32_t zstd_mf_hash4(const uint8_t * data, unsigned hash_log) {
  // Simple multiplicative hash
  uint32_t val = gcomp_read_le32(data);
  return (val * 0x9E3779B1U) >> (32 - hash_log);
}

/**
 * @brief Compute hash for 5 bytes (better distribution for larger tables).
 */
static inline uint32_t zstd_mf_hash5(const uint8_t * data, unsigned hash_log) {
  uint64_t val = gcomp_read_le32(data);
  val |= ((uint64_t)data[4]) << 32;
  return (uint32_t)((val * 0x870DD5849ULL) >> (40 - hash_log));
}

//
// Effort by Level
//

/**
 * @brief How hard one compression level searches.
 *
 * RFC 8878 says nothing about levels.  It describes the frame, not how to
 * choose what goes in it, so a level is a promise about how much work the
 * encoder will spend and the only way to set one is to measure.
 *
 * TWENTY-TWO LEVELS THAT WERE FIVE
 * ================================
 *
 * These were set by range tests -- level <= 3, level <= 6, level <= 12 -- and
 * the ranges made levels into aliases of one another.  Compressing 11 MB of
 * source, manuals, XML and an ELF binary at each level in turn produced byte
 * for byte identical output from levels 2 and 3; from 4, 5 and 6; from 7, 8, 9
 * and 10; and from 11 and 12.  Twelve levels, five behaviours.  A caller who
 * asked for 9 got 7.
 *
 * This is the same defect the deflate encoder had, found the same way and
 * fixed the same way: a table with one row per level, because there are
 * twenty-two levels.
 *
 * `search_depth` is how many hash chain candidates a position considers,
 * `lazy_depth` how many times a match may be deferred in favour of a better
 * one at the next position (zero is a greedy parse), and `nice_length` the
 * match length at which the chain walk stops looking for something better.
 */
typedef struct {
  unsigned search_depth; ///< Maximum chain search depth.
  unsigned lazy_depth;   ///< Positions a match may be deferred through.
  uint32_t nice_length;  ///< Length at which a match is taken as it stands.
  unsigned hash_log;     ///< Log2 of the hash table size.
} zstd_effort_t;

/// Indexed by compression level; entry 0 is unused (level 0 means "default").
static const zstd_effort_t k_zstd_effort[23] = {
    {0, 0, 0, 0},       // 0: unused
    {4, 0, 128, 14},    // 1: greedy, and fast because of it
    {8, 1, 128, 14},    // 2
    {16, 1, 128, 15},   // 3
    {24, 1, 128, 16},   // 4
    {48, 1, 128, 16},   // 5
    {64, 1, 128, 16},   // 6
    {128, 2, 192, 17},  // 7
    {192, 2, 192, 17},  // 8
    {256, 2, 192, 17},  // 9
    {320, 2, 192, 17},  // 10
    {384, 2, 192, 17},  // 11
    {448, 2, 192, 17},  // 12
    {512, 2, 256, 18},  // 13
    {640, 2, 256, 18},  // 14
    {768, 2, 256, 18},  // 15
    {896, 2, 256, 18},  // 16
    {1024, 2, 256, 18}, // 17
    {1280, 2, 256, 18}, // 18
    {1536, 2, 256, 18}, // 19
    {1792, 2, 256, 18}, // 20
    {2048, 2, 256, 18}, // 21
    {2560, 2, 256, 18}, // 22
};

/**
 * @brief The effort settings for @p level, clamped to the table.
 */
static const zstd_effort_t * zstd_mf_effort(int level) {
  if (level < 1) {
    level = 3;
  }
  if (level > 22) {
    level = 22;
  }
  return &k_zstd_effort[level];
}

//
// Match Cost Model
//

/**
 * @brief Nominal bit cost charged to one literal byte.
 *
 * Literals are Huffman-coded and so usually cost less than eight bits; eight
 * is used because this number's only job is to set the exchange rate between
 * a byte of match length and a bit of offset, and overstating it makes the
 * comparison lean towards the longer match.
 */
#define MF_LITERAL_BITS 8

/**
 * @brief Bits an offset's extra-bits field occupies.
 *
 * A new offset is written as the value offset+3 (offset codes 1-3 name the
 * repeat offsets), and RFC 8878 section 3.1.1.3.2.1.1 writes an offset of
 * value v under code floor(log2(v)) followed by that many raw bits.  The code
 * itself is FSE-coded and its cost varies with the block; the raw bits do not,
 * so they are what is counted here.
 */
static inline unsigned zstd_mf_offset_bits(uint32_t offset) {
  uint32_t v = offset + 3;
  unsigned bits = 0;
  while (v > 1) {
    v >>= 1;
    bits++;
  }
  return bits;
}

/**
 * @brief Bits a match saves over writing its bytes as literals.
 *
 * Positive is better.  The constant part of a sequence's cost -- the literal
 * length code, the match length code, the offset code itself -- is left out
 * because it is very nearly the same for both candidates being compared and
 * so cancels.
 */
static inline int64_t zstd_mf_match_gain(uint32_t length, uint32_t offset) {
  return (int64_t)length * MF_LITERAL_BITS -
      (int64_t)zstd_mf_offset_bits(offset);
}


//
// Match Finder Implementation
//

/**
 * @brief Initialize match finder.
 */
gcomp_status_t zstd_mf_init(zstd_match_finder_t * mf,
    const gcomp_allocator_t * alloc, int level, size_t window_size,
    gcomp_memory_tracker_t * mem_tracker) {
  if (!mf || !alloc) {
    return GCOMP_ERR_INVALID_ARG;
  }

  memset(mf, 0, sizeof(*mf));

  const zstd_effort_t * effort = zstd_mf_effort(level);

  // Clamp the hash table to the window size: there is no point having more
  // hash entries than there are positions to put in them.
  unsigned hash_log = effort->hash_log;
  while (hash_log > MF_HASH_LOG_MIN && ((size_t)1 << hash_log) > window_size) {
    hash_log--;
  }

  mf->hash_log = hash_log;
  mf->hash_size = (size_t)1 << hash_log;
  mf->window_size = window_size;
  mf->search_depth = effort->search_depth;
  mf->lazy_depth = effort->lazy_depth;
  mf->nice_length = effort->nice_length;

  // The chain table is indexed by position in the match finder's window, and
  // that window now holds the history carried across blocks as well as the
  // block being compressed.  Sizing it to one block, as it was, meant no
  // position past the first 128 KB could be chained at all.
  mf->chain_size = (size_t)window_size + ZSTD_BLOCK_SIZE_MAX;

  // Allocate hash table (use calloc to initialize to zero)
  mf->hash_table = gcomp_calloc(alloc, mf->hash_size, sizeof(uint32_t));
  if (!mf->hash_table) {
    return GCOMP_ERR_MEMORY;
  }
  if (mem_tracker) {
    gcomp_memory_track_alloc(mem_tracker, mf->hash_size * sizeof(uint32_t));
  }

  // Allocate chain table (use calloc to initialize to zero)
  mf->chain_table = gcomp_calloc(alloc, mf->chain_size, sizeof(uint32_t));
  if (!mf->chain_table) {
    gcomp_free(alloc, mf->hash_table);
    mf->hash_table = NULL;
    return GCOMP_ERR_MEMORY;
  }
  if (mem_tracker) {
    gcomp_memory_track_alloc(mem_tracker, mf->chain_size * sizeof(uint32_t));
  }

  return GCOMP_OK;
}

/**
 * @brief Destroy match finder.
 */
void zstd_mf_destroy(zstd_match_finder_t * mf, const gcomp_allocator_t * alloc,
    gcomp_memory_tracker_t * mem_tracker) {
  if (!mf) {
    return;
  }

  if (mf->hash_table) {
    if (mem_tracker) {
      gcomp_memory_track_free(mem_tracker, mf->hash_size * sizeof(uint32_t));
    }
    gcomp_free(alloc, mf->hash_table);
    mf->hash_table = NULL;
  }

  if (mf->chain_table) {
    if (mem_tracker) {
      gcomp_memory_track_free(mem_tracker, mf->chain_size * sizeof(uint32_t));
    }
    gcomp_free(alloc, mf->chain_table);
    mf->chain_table = NULL;
  }
}

/**
 * @brief Reset match finder for new block.
 */
void zstd_mf_reset(zstd_match_finder_t * mf) {
  if (!mf) {
    return;
  }

  if (mf->hash_table) {
    memset(mf->hash_table, 0, mf->hash_size * sizeof(uint32_t));
  }
  if (mf->chain_table) {
    memset(mf->chain_table, 0, mf->chain_size * sizeof(uint32_t));
  }
}

//
// Match Structure
//

typedef struct {
  uint32_t offset; ///< Match offset (distance back)
  uint32_t length; ///< Match length
} zstd_match_t;

/**
 * @brief Decide whether to give up @p here in favour of @p later, one byte on.
 *
 * Reaching @p later means writing the byte at the current position as a
 * literal, so @p later must be worth more than @p here by at least what that
 * literal costs before the exchange is worth making.  Without that margin the
 * parse would drift forward one byte at a time chasing matches no better than
 * the one it already had.
 */
static inline bool zstd_mf_prefer_later(
    const zstd_match_t * later, const zstd_match_t * here) {
  return zstd_mf_match_gain(later->length, later->offset) >
      zstd_mf_match_gain(here->length, here->offset) + MF_LITERAL_BITS;
}

/**
 * @brief Count how many bytes match at two positions.
 *
 * Eight bytes at a time while eight remain.  Both reads are in bounds: the
 * loop only runs while p1 + 8 is within p1_end, which is the end of the
 * buffer, and p2 is always behind p1 -- a match source is earlier than the
 * position matching it -- so p2 + 8 is further inside the buffer still.
 *
 * Where the two words differ, the first differing byte is the lowest
 * differing bit of their exclusive-or, divided by eight.  Reading both
 * little-endian puts the earliest byte in memory in the low bits, so this
 * counts forwards through memory on either byte order.
 *
 * This is the comparison that decides every candidate match, and one byte
 * per iteration made it 5% of encoding on its own.
 */
static inline size_t zstd_mf_count_match(
    const uint8_t * p1, const uint8_t * p2, const uint8_t * p1_end) {
  const uint8_t * anchor = p1;

  while (p1 + 8 <= p1_end) {
    uint64_t a = gcomp_read_le64(p1);
    uint64_t b = gcomp_read_le64(p2);
    if (a != b) {
      return (size_t)(p1 - anchor) +
          (size_t)((unsigned)__builtin_ctzll(a ^ b) >> 3);
    }
    p1 += 8;
    p2 += 8;
  }

  while (p1 < p1_end && *p1 == *p2) {
    p1++;
    p2++;
  }
  return (size_t)(p1 - anchor);
}

/**
 * @brief Find best match at current position.
 *
 * @param mf Match finder context
 * @param data Input data
 * @param pos Current position
 * @param data_size Total data size
 * @param insert Whether to add @p pos to the tables as it is searched.  A
 *        position must be inserted exactly once: inserting it twice makes its
 *        chain entry point at itself, which the walk below reads as the end of
 *        the chain and so throws away every older candidate behind it.
 *        Deferred matching searches a position before the parse reaches it, so
 *        the caller tracks which positions that search has already covered.
 * @param match_out Output: best match found
 * @return true if match found, false otherwise
 */
static bool zstd_mf_find_match(zstd_match_finder_t * mf, const uint8_t * data,
    size_t pos, size_t data_size, bool insert, zstd_match_t * match_out) {
  // Need at least MF_HASH_READ_SIZE bytes for hash function
  if (pos + MF_HASH_READ_SIZE > data_size) {
    return false;
  }

  // Hash the current position
  uint32_t hash = zstd_mf_hash4(data + pos, mf->hash_log);
  uint32_t chain_pos = mf->hash_table[hash];

  if (insert) {
    // Update hash table with current position (for future references)
    mf->hash_table[hash] = (uint32_t)(pos + 1); // +1 so 0 means "no entry"

    // Update chain table
    if (pos < mf->chain_size) {
      mf->chain_table[pos] = chain_pos;
    }
  }

  // No previous position at this hash
  if (chain_pos == 0) {
    return false;
  }
  chain_pos--; // Convert back from 1-based to 0-based

  // Search the chain for best match
  size_t best_len = MF_MIN_MATCH - 1;
  size_t best_offset = 0;
  const uint8_t * const limit = data + data_size;
  unsigned depth = mf->search_depth;

  while (depth > 0 && chain_pos < pos) {
    size_t offset = pos - chain_pos;

    // Check if offset is too large.  The window the frame header declares is
    // a promise to the decoder about how far back it must keep data (RFC 8878
    // section 3.1.1.1.2); a sequence that reaches further is not decodable.
    if (offset > MF_MAX_DISTANCE || offset > pos ||
        offset > mf->window_size) {
      break;
    }

    // Quick check: compare first and last bytes before full comparison
    // Ensure we don't read past the end of the buffer
    if (pos + best_len < data_size && data[chain_pos] == data[pos] &&
        data[chain_pos + best_len] == data[pos + best_len]) {
      // Count matching bytes
      size_t match_len =
          zstd_mf_count_match(data + pos, data + chain_pos, limit);

      if (match_len > best_len) {
        best_len = match_len;
        best_offset = offset;

        // A match this long is taken as it stands; see nice_length.
        if (match_len >= mf->nice_length) {
          break;
        }
      }
    }

    // Follow chain
    if (chain_pos < mf->chain_size) {
      uint32_t next = mf->chain_table[chain_pos];
      if (next == 0 || next - 1 >= chain_pos) {
        break; // End of chain or invalid
      }
      chain_pos = next - 1;
    }
    else {
      break;
    }

    depth--;
  }

  if (best_len >= MF_MIN_MATCH && best_offset > 0) {
    match_out->offset = (uint32_t)best_offset;
    match_out->length = (uint32_t)best_len;
    return true;
  }

  return false;
}

/**
 * @brief Insert position into hash table without searching.
 *
 * Used for positions we're skipping (e.g., inside a match).
 */
static void zstd_mf_insert(zstd_match_finder_t * mf, const uint8_t * data,
    size_t pos, size_t data_size) {
  // Need at least MF_HASH_READ_SIZE bytes for hash function
  if (pos + MF_HASH_READ_SIZE > data_size) {
    return;
  }

  uint32_t hash = zstd_mf_hash4(data + pos, mf->hash_log);
  uint32_t prev = mf->hash_table[hash];
  mf->hash_table[hash] = (uint32_t)(pos + 1);

  if (pos < mf->chain_size) {
    mf->chain_table[pos] = prev;
  }
}

void zstd_mf_slide(zstd_match_finder_t * mf, size_t shift) {
  if (!mf || shift == 0) {
    return;
  }

  // Entries name positions in the window, so moving the window moves every
  // entry with it.  A position that falls off the front is dropped: the byte
  // it named is no longer there to match against.  Zero means "no entry", so
  // it is both the empty value and what a dropped entry becomes.
  for (size_t i = 0; i < mf->hash_size; i++) {
    uint32_t v = mf->hash_table[i];
    mf->hash_table[i] = (v > shift) ? (uint32_t)(v - shift) : 0u;
  }

  if (shift >= mf->chain_size) {
    memset(mf->chain_table, 0, mf->chain_size * sizeof(uint32_t));
    return;
  }
  size_t kept = mf->chain_size - shift;
  memmove(mf->chain_table, mf->chain_table + shift, kept * sizeof(uint32_t));
  memset(mf->chain_table + kept, 0, shift * sizeof(uint32_t));
  for (size_t i = 0; i < kept; i++) {
    uint32_t v = mf->chain_table[i];
    mf->chain_table[i] = (v > shift) ? (uint32_t)(v - shift) : 0u;
  }
}

void zstd_mf_index_range(zstd_match_finder_t * mf, const uint8_t * data,
    size_t from, size_t to, size_t data_size) {
  if (!mf || !data) {
    return;
  }
  for (size_t i = from; i < to && i + MF_HASH_READ_SIZE <= data_size; i++) {
    zstd_mf_insert(mf, data, i, data_size);
  }
}

//
// Sequence Generation
//

/**
 * @brief Generate sequences from input data using match finder.
 *
 * @param mf Match finder context
 * @param data Window contents: history followed by the block to encode
 * @param data_size Total bytes in @p data
 * @param start_pos First position to encode; everything before it is history
 *        that the caller has already indexed
 * @param sequences Output sequence array
 * @param max_sequences Maximum sequences to generate
 * @param num_sequences_out Output: number of sequences generated
 * @param literals_out Output: literals buffer (caller provides)
 * @param literals_size_out Output: total literals size
 * @return GCOMP_OK on success
 */
gcomp_status_t zstd_mf_generate_sequences(zstd_match_finder_t * mf,
    const uint8_t * data, size_t data_size, size_t start_pos,
    zstd_sequence_t * sequences, size_t max_sequences,
    size_t * num_sequences_out, uint8_t * literals_out,
    size_t * literals_size_out, uint32_t * rep_offset_1,
    uint32_t * rep_offset_2, uint32_t * rep_offset_3) {
  if (!mf || !data || !sequences || !num_sequences_out || !literals_out ||
      !literals_size_out) {
    return GCOMP_ERR_INVALID_ARG;
  }

  // The tables are not reset here and the history before start_pos is not
  // re-indexed.  Both belong to the caller: a stream's blocks share one
  // window, so each block's history is the previous blocks, already indexed
  // as they were encoded.  Resetting here made every block start from nothing
  // - no match could cross a block boundary, and on a multi-megabyte file
  // that threw the history away 128 KB at a time.
  size_t pos = start_pos;
  size_t lit_start = start_pos;
  size_t num_seq = 0;
  size_t lit_pos = 0;

  uint32_t rep1 = rep_offset_1 ? *rep_offset_1 : ZSTD_REP_OFFSET_1_INIT;
  uint32_t rep2 = rep_offset_2 ? *rep_offset_2 : ZSTD_REP_OFFSET_2_INIT;
  uint32_t rep3 = rep_offset_3 ? *rep_offset_3 : ZSTD_REP_OFFSET_3_INIT;

  while (pos < data_size && num_seq < max_sequences) {
    zstd_match_t match;

    // Try to find a match
    if (zstd_mf_find_match(mf, data, pos, data_size, true, &match)) {
      // Deferred matching: a match here blocks every match that starts inside
      // it, so before committing, look one byte on and keep whichever is
      // worth more.  `indexed` is the highest position these look-ahead
      // searches have put into the tables; the fill loop below must not
      // insert those a second time.
      size_t indexed = pos;
      unsigned deferrals = mf->lazy_depth;
      while (deferrals > 0 && match.length < mf->nice_length &&
          pos + 1 < data_size) {
        zstd_match_t later;
        bool found =
            zstd_mf_find_match(mf, data, pos + 1, data_size, true, &later);
        indexed = pos + 1;
        if (!found || !zstd_mf_prefer_later(&later, &match)) {
          break;
        }
        // Give up the match here; this byte becomes one more literal.
        pos++;
        match = later;
        deferrals--;
      }

      // Convert to encoded offset (zstd uses codes 1-3 for repeat offsets)
      // Note: When lit_length == 0, offset encoding is different:
      //   offset 1 -> rep_offset_2
      //   offset 2 -> rep_offset_3
      //   offset 3 -> rep_offset_1 - 1
      // To avoid this complexity, we use new offset encoding when lit_length==0
      // and the match is a repeat offset.
      uint32_t encoded_offset = match.offset;
      size_t lit_len = pos - lit_start;

      if (lit_len > 0) {
        // Normal case: lit_length > 0
        if (match.offset == rep1) {
          encoded_offset = 1;
          // rep1 stays the same
        }
        else if (match.offset == rep2) {
          encoded_offset = 2;
          // Swap rep1 and rep2
          uint32_t tmp = rep2;
          rep2 = rep1;
          rep1 = tmp;
        }
        else if (match.offset == rep3) {
          encoded_offset = 3;
          // Rotate offsets
          uint32_t tmp = rep3;
          rep3 = rep2;
          rep2 = rep1;
          rep1 = tmp;
        }
        else {
          // New offset: add 3 (offset codes 1-3 are for repeat offsets)
          encoded_offset = match.offset + 3;
          // Update repeat offsets
          rep3 = rep2;
          rep2 = rep1;
          rep1 = match.offset;
        }
      }
      else {
        // Special case: lit_length == 0
        // When lit_length is 0, repeat offset codes are shifted:
        //   offset 1 -> rep_offset_2
        //   offset 2 -> rep_offset_3
        //   offset 3 -> rep_offset_1 - 1
        // For simplicity, we always encode as new offset to avoid this
        // complexity. This is less efficient but correct.
        encoded_offset = match.offset + 3;
        rep3 = rep2;
        rep2 = rep1;
        rep1 = match.offset;
      }

      // Copy literals before this match (lit_len computed above)
      memcpy(literals_out + lit_pos, data + lit_start, lit_len);
      lit_pos += lit_len;

      // Record sequence
      sequences[num_seq].lit_length = (uint32_t)lit_len;
      sequences[num_seq].match_offset = encoded_offset;
      sequences[num_seq].match_length = match.length;
      num_seq++;

      // Advance position
      // Insert intermediate positions into hash table for better chaining,
      // skipping any the deferral search above already inserted.
      size_t match_end = pos + match.length;
      size_t fill_from = (indexed > pos) ? indexed + 1 : pos + 1;
      for (size_t i = fill_from;
           i < match_end && i + MF_HASH_READ_SIZE <= data_size; i++) {
        zstd_mf_insert(mf, data, i, data_size);
      }

      pos = match_end;
      lit_start = pos;
    }
    else {
      // No match found, advance by one
      pos++;
    }
  }

  // Copy remaining literals
  if (lit_start < data_size) {
    size_t remaining = data_size - lit_start;
    memcpy(literals_out + lit_pos, data + lit_start, remaining);
    lit_pos += remaining;
  }

  *num_sequences_out = num_seq;
  *literals_size_out = lit_pos;

  // Update repeat offsets
  if (rep_offset_1)
    *rep_offset_1 = rep1;
  if (rep_offset_2)
    *rep_offset_2 = rep2;
  if (rep_offset_3)
    *rep_offset_3 = rep3;

  return GCOMP_OK;
}
