/**
 * @file zstd_matchfinder.c
 *
 * Match finding for Zstandard encoder in the Ghoti.io Compress library.
 *
 * ## Algorithm Overview
 *
 * This implements a hash chain match finder for LZ77-style compression:
 * - Each position is hashed using a 4-byte (or 5-byte) hash
 * - Hash collisions form a chain (linked list via chain_table)
 * - To find matches, look up the hash and follow the chain
 * - Chain depth is tuned by compression level
 *
 * ## Data Structures
 *
 * - **hash_table[hash]**: Position+1 of the most recent occurrence of this hash
 *   (0 means no entry). Positions are stored as value+1 to distinguish from
 *   "no entry" (which would be position 0 for the first byte).
 *
 * - **chain_table[pos]**: Position+1 of the previous occurrence with same hash.
 *   Forms a linked list of candidates to check for matches.
 *
 * ## Compression Levels
 *
 * Higher levels search more chain entries for potentially longer matches:
 *
 * | Level | Search Depth | Speed  | Compression |
 * |-------|--------------|--------|-------------|
 * | 1     | 4            | Fast   | Low         |
 * | 2-3   | 16           | Fast   | Low-Medium  |
 * | 4-6   | 64           | Medium | Medium      |
 * | 7-12  | 256          | Slow   | High        |
 * | 13-22 | 512+         | Slow   | Highest     |
 *
 * ## Sequence Generation
 *
 * Sequences are generated by scanning input and finding matches:
 *
 * 1. At each position, try to find a match using the hash chain
 * 2. If a match is found:
 *    - Record literals since last match (literal_length)
 *    - Record match offset (distance back to match source)
 *    - Record match length
 *    - Advance past the match, inserting intermediate positions into hash
 * 3. If no match, advance by one byte
 * 4. After scanning, append remaining bytes as trailing literals
 *
 * ## Deferred ("Lazy") Matching
 *
 * Step 2 above, taken on its own, is a greedy parse: the first match found is
 * always the one emitted.  Greedy is not optimal, and the reason is easy to
 * state.  A match found at position p blocks every match that starts inside
 * it.  If the position one byte later begins a match that is long enough to
 * pay for the literal that reaching it costs, emitting the literal and taking
 * the later match encodes more of the input for the same number of bits.
 *
 * So before committing to a match, the finder searches the next position as
 * well and keeps whichever of the two is worth more.  It may do this more
 * than once -- `lazy_depth` says how many times -- walking forward one byte at
 * a time for as long as each step keeps improving.
 *
 * "Worth more" is decided by zstd_mf_match_gain(), which is a bit-cost model,
 * not a length comparison: a longer match reached through a more distant
 * offset can cost more bits than a shorter one close by, because the offset's
 * extra bits are written raw (RFC 8878 section 3.1.1.3.2.1.1).
 *
 * The search stops early once a match reaches `nice_length`, on the grounds
 * that a match that long will not plausibly be beaten by enough to justify
 * the search, and both knobs are zero/low at the fast levels where the point
 * of the level is to not do this.
 *
 * ## Repeat Offset Handling
 *
 * Zstd uses "repeat offsets" to efficiently encode common patterns:
 * - rep_offset_1, rep_offset_2, rep_offset_3 track recent offsets
 * - When a match uses the same offset as a recent one, encode it as 1, 2, or 3
 * - This saves bits compared to encoding the full offset
 *
 * Special case: When literal_length == 0 (adjacent matches), the repeat offset
 * codes are shifted. To avoid complexity, we don't use repeat offsets when
 * literal_length is 0.
 *
 * Reference: RFC 8878 (https://www.rfc-editor.org/rfc/rfc8878.html)
 *
 * Copyright 2026 by Corey Pennycuff
 */

#define _POSIX_C_SOURCE 200809L

#include <ghoti.io/compress/macros.h>
#include "../../core/endian.h"
#ifdef GCOMP_TEST_BUILD
#include <assert.h>
#endif
#include "zstd_internal.h"
#include "zstd_matchfinder_private.h"
#include <string.h>

//
// Match Finder Constants
//

// MF_MIN_MATCH, MF_HASH_READ_SIZE and MF_MAX_DISTANCE are in
// zstd_matchfinder_private.h, which the optimal parse shares.
#define MF_HASH_LOG_DEFAULT 17   ///< Default hash table log (128K entries)
#define MF_HASH_LOG_MIN 12       ///< Minimum hash table log
#define MF_HASH_LOG_MAX 20       ///< Maximum hash table log
#define MF_CHAIN_LOG_DEFAULT 16  ///< Default chain table log (64K entries)

/// Most positions the binary tree will hold: two slots of four bytes each,
/// so this is a 64 MiB ceiling on the tree.  See zstd_mf_init().
#define MF_BT_MAX_ENTRIES (8u * 1024u * 1024u)

//
// Hash Functions
//

/**
 * @brief Compute hash for 4 bytes.
 */
static inline uint32_t zstd_mf_hash4(const uint8_t * data, unsigned hash_log) {
  // Simple multiplicative hash
  uint32_t val = gcomp_read_le32(data);
  return (val * 0x9E3779B1U) >> (32 - hash_log);
}

/**
 * @brief Compute hash for 5 bytes (better distribution for larger tables).
 */
static inline uint32_t zstd_mf_hash5(const uint8_t * data, unsigned hash_log) {
  uint64_t val = gcomp_read_le32(data);
  val |= ((uint64_t)data[4]) << 32;
  return (uint32_t)((val * 0x870DD5849ULL) >> (40 - hash_log));
}

//
// Effort by Level
//

/**
 * @brief How hard one compression level searches.
 *
 * RFC 8878 says nothing about levels.  It describes the frame, not how to
 * choose what goes in it, so a level is a promise about how much work the
 * encoder will spend and the only way to set one is to measure.
 *
 * TWENTY-TWO LEVELS THAT WERE FIVE
 * ================================
 *
 * These were set by range tests -- level <= 3, level <= 6, level <= 12 -- and
 * the ranges made levels into aliases of one another.  Compressing 11 MB of
 * source, manuals, XML and an ELF binary at each level in turn produced byte
 * for byte identical output from levels 2 and 3; from 4, 5 and 6; from 7, 8, 9
 * and 10; and from 11 and 12.  Twelve levels, five behaviours.  A caller who
 * asked for 9 got 7.
 *
 * This is the same defect the deflate encoder had, found the same way and
 * fixed the same way: a table with one row per level, because there are
 * twenty-two levels.
 *
 * `search_depth` is how many hash chain candidates a position considers,
 * `lazy_depth` how many times a match may be deferred in favour of a better
 * one at the next position (zero is a greedy parse), and `nice_length` the
 * match length at which the chain walk stops looking for something better.
 */
typedef struct {
  unsigned search_depth; ///< Candidates examined; see the table below.
  unsigned lazy_depth;   ///< Positions a match may be deferred through.
  uint32_t nice_length;  ///< Length at which a match is taken as it stands.
  unsigned hash_log;     ///< Log2 of the hash table size.
  unsigned use_bt;       ///< Search a binary tree rather than a hash chain.
} zstd_effort_t;

/// Indexed by compression level; entry 0 is unused (level 0 means "default").
// `search_depth` counts candidates examined, and what a candidate costs
// changes at level 11 where the chain gives way to the tree -- so the numbers
// change scale there too, and the two halves are not comparable.
//
// A chain step crosses off one position and learns nothing for the next, so
// the only way to search harder is to walk further and the counts run into
// the hundreds.  A tree step halves what is left, and a descent takes six
// steps on average.  A bound of 128 would never once be reached: when these
// levels first moved to the tree, levels 11 through 22 became four encoders
// wearing twelve numbers, because the only thing separating most of them
// was a bound that no longer bound anything.
//
// `nice_length` turned out to be the knob that matters for the tree, far
// more than the depth.  Reaching it stops the descent, and stopping the
// descent closes off whatever was still below -- so it does not only end
// this search, it makes the tree smaller for every search after.  On 9 MB of
// manuals, C source and XML at a fixed depth of 32, raising it from 64 to
// 4096 took the output from 1,602,010 bytes to 1,527,249, while depth beyond
// about 24 was worth almost nothing.
static const zstd_effort_t k_zstd_effort[23] = {
    {0, 0, 0, 0, 0},          // 0: unused
    {4, 0, 128, 14, 0},       // 1: greedy, and fast because of it
    {8, 1, 128, 14, 0},       // 2
    {16, 1, 128, 15, 0},      // 3
    {24, 1, 128, 16, 0},      // 4
    {48, 1, 128, 16, 0},      // 5
    {64, 1, 128, 16, 0},      // 6
    {128, 2, 192, 17, 0},     // 7
    {192, 2, 192, 17, 0},     // 8
    {256, 2, 192, 17, 0},     // 9
    {320, 2, 192, 17, 0},     // 10: last of the chain levels
    {18, 2, 768, 17, 1},      // 11: first of the tree levels
    {20, 2, 1024, 17, 1},     // 12
    {22, 2, 1280, 18, 1},     // 13
    {24, 2, 1536, 18, 1},     // 14
    {26, 2, 2048, 18, 1},     // 15
    {28, 2, 2560, 18, 1},     // 16
    {32, 2, 3072, 18, 1},     // 17
    {36, 2, 3584, 18, 1},     // 18
    {40, 3, 4096, 18, 1},     // 19: one more deferral is what is left
    {44, 3, 5120, 18, 1},     // 20
    {52, 3, 8192, 18, 1},     // 21
    {64, 3, 12288, 18, 1}     // 22
};

/**
 * @brief The effort settings for @p level, clamped to the table.
 */
static const zstd_effort_t * zstd_mf_effort(int level) {
  if (level < 1) {
    level = 3;
  }
  if (level > 22) {
    level = 22;
  }
  return &k_zstd_effort[level];
}

//
// Match Cost Model
//

/**
 * @brief Nominal bit cost charged to one literal byte.
 *
 * Literals are Huffman-coded and so usually cost less than eight bits; eight
 * is used because this number's only job is to set the exchange rate between
 * a byte of match length and a bit of offset, and overstating it makes the
 * comparison lean towards the longer match.
 */
#define MF_LITERAL_BITS 8

/**
 * @brief Bits an offset's extra-bits field occupies.
 *
 * A new offset is written as the value offset+3 (offset codes 1-3 name the
 * repeat offsets), and RFC 8878 section 3.1.1.3.2.1.1 writes an offset of
 * value v under code floor(log2(v)) followed by that many raw bits.  The code
 * itself is FSE-coded and its cost varies with the block; the raw bits do not,
 * so they are what is counted here.
 */
static inline unsigned zstd_mf_offset_bits(uint32_t offset) {
  uint32_t v = offset + 3;
  unsigned bits = 0;
  while (v > 1) {
    v >>= 1;
    bits++;
  }
  return bits;
}

/**
 * @brief Bits a match saves over writing its bytes as literals.
 *
 * Positive is better.  The constant part of a sequence's cost -- the literal
 * length code, the match length code, the offset code itself -- is left out
 * because it is very nearly the same for both candidates being compared and
 * so cancels.
 */
static inline int64_t zstd_mf_match_gain(uint32_t length, uint32_t offset) {
  return (int64_t)length * MF_LITERAL_BITS -
      (int64_t)zstd_mf_offset_bits(offset);
}


//
// Match Finder Implementation
//

/**
 * @brief Initialize match finder.
 */
gcomp_status_t zstd_mf_init(zstd_match_finder_t * mf,
    const gcomp_allocator_t * alloc, int level, size_t window_size,
    gcomp_memory_tracker_t * mem_tracker) {
  if (!mf || !alloc) {
    return GCOMP_ERR_INVALID_ARG;
  }

  memset(mf, 0, sizeof(*mf));

  const zstd_effort_t * effort = zstd_mf_effort(level);

  // Clamp the hash table to the window size: there is no point having more
  // hash entries than there are positions to put in them.
  unsigned hash_log = effort->hash_log;
  while (hash_log > MF_HASH_LOG_MIN && ((size_t)1 << hash_log) > window_size) {
    hash_log--;
  }

  mf->hash_log = hash_log;
  mf->hash_size = (size_t)1 << hash_log;
  mf->window_size = window_size;
  mf->search_depth = effort->search_depth;
  mf->lazy_depth = effort->lazy_depth;
  mf->nice_length = effort->nice_length;

  // The chain table is indexed by position in the match finder's window, and
  // that window now holds the history carried across blocks as well as the
  // block being compressed.  Sizing it to one block, as it was, meant no
  // position past the first 128 KB could be chained at all.
  mf->chain_size = (size_t)window_size + ZSTD_BLOCK_SIZE_MAX;

  // How far back the tree can reach, and what it costs.
  //
  // Slots are indexed by position modulo bt_size, so bt_size must be a power
  // of two, and a match may only reach back less than that far -- otherwise
  // two positions in play at once would share a pair of slots and one would
  // overwrite the other's children.  Reaching less far than bt_size is all
  // that is needed: inserting a position overwrites the slot of one at least
  // bt_size behind it, and that one is already too far back to be followed.
  //
  // So bt_size is rounded DOWN to a power of two, not up.  Rounding up would
  // very nearly double a table that is already two slots per position where
  // the chain was one: at the top levels, which declare a 32 MB window, that
  // asked for 536 MB against a 256 MiB budget and simply failed to encode.
  // Rounding down spends no more than the chain did and gives up a little
  // reach instead.
  //
  // The cap is the same trade taken further.  A declared window is a promise
  // to the decoder about how much history it must keep (RFC 8878 section
  // 3.1.1.1.2), not an undertaking to search all of it, so the tree searches
  // what fits in its budget and the frame stays exactly as valid.
  mf->use_bt = effort->use_bt;
  if (mf->use_bt) {
    size_t n = 1;
    while (n < mf->chain_size && n < MF_BT_MAX_ENTRIES) {
      n <<= 1;
    }
    mf->bt_size = n;
    mf->bt_mask = n - 1;
  }
  mf->base_pos = 0;

  // Allocate hash table (use calloc to initialize to zero)
  mf->hash_table = gcomp_calloc(alloc, mf->hash_size, sizeof(uint32_t));
  if (!mf->hash_table) {
    return GCOMP_ERR_MEMORY;
  }
  if (mem_tracker) {
    gcomp_memory_track_alloc(mem_tracker, mf->hash_size * sizeof(uint32_t));
  }

  // Allocate whichever of the two the level asked for.  A level uses the
  // chain or the tree, never both, so only one is paid for.
  if (mf->use_bt) {
    mf->bt_table = gcomp_calloc(alloc, mf->bt_size * 2u, sizeof(uint32_t));
    if (!mf->bt_table) {
      gcomp_free(alloc, mf->hash_table);
      mf->hash_table = NULL;
      return GCOMP_ERR_MEMORY;
    }
    if (mem_tracker) {
      gcomp_memory_track_alloc(
          mem_tracker, mf->bt_size * 2u * sizeof(uint32_t));
    }
    return GCOMP_OK;
  }

  // Allocate chain table (use calloc to initialize to zero)
  mf->chain_table = gcomp_calloc(alloc, mf->chain_size, sizeof(uint32_t));
  if (!mf->chain_table) {
    gcomp_free(alloc, mf->hash_table);
    mf->hash_table = NULL;
    return GCOMP_ERR_MEMORY;
  }
  if (mem_tracker) {
    gcomp_memory_track_alloc(mem_tracker, mf->chain_size * sizeof(uint32_t));
  }

  return GCOMP_OK;
}

/**
 * @brief Destroy match finder.
 */
void zstd_mf_destroy(zstd_match_finder_t * mf, const gcomp_allocator_t * alloc,
    gcomp_memory_tracker_t * mem_tracker) {
  if (!mf) {
    return;
  }

  if (mf->hash_table) {
    if (mem_tracker) {
      gcomp_memory_track_free(mem_tracker, mf->hash_size * sizeof(uint32_t));
    }
    gcomp_free(alloc, mf->hash_table);
    mf->hash_table = NULL;
  }

  if (mf->chain_table) {
    if (mem_tracker) {
      gcomp_memory_track_free(mem_tracker, mf->chain_size * sizeof(uint32_t));
    }
    gcomp_free(alloc, mf->chain_table);
    mf->chain_table = NULL;
  }

  if (mf->bt_table) {
    if (mem_tracker) {
      gcomp_memory_track_free(
          mem_tracker, mf->bt_size * 2u * sizeof(uint32_t));
    }
    gcomp_free(alloc, mf->bt_table);
    mf->bt_table = NULL;
  }
}

/**
 * @brief Reset match finder for new block.
 */
void zstd_mf_reset(zstd_match_finder_t * mf) {
  if (!mf) {
    return;
  }

  if (mf->hash_table) {
    memset(mf->hash_table, 0, mf->hash_size * sizeof(uint32_t));
  }
  if (mf->chain_table) {
    memset(mf->chain_table, 0, mf->chain_size * sizeof(uint32_t));
  }
  if (mf->bt_table) {
    memset(mf->bt_table, 0, mf->bt_size * 2u * sizeof(uint32_t));
  }
  // Nothing refers to any position any more, so where data[0] sits in the
  // stream stops mattering and counting can start again.
  mf->base_pos = 0;
}

//
// Match Structure
//

typedef struct {
  uint32_t offset; ///< Match offset (distance back)
  uint32_t length; ///< Match length
} zstd_match_t;

/**
 * @brief Decide whether to give up @p here in favour of @p later, one byte on.
 *
 * Reaching @p later means writing the byte at the current position as a
 * literal, so @p later must be worth more than @p here by at least what that
 * literal costs before the exchange is worth making.  Without that margin the
 * parse would drift forward one byte at a time chasing matches no better than
 * the one it already had.
 */
static inline bool zstd_mf_prefer_later(
    const zstd_match_t * later, const zstd_match_t * here) {
  return zstd_mf_match_gain(later->length, later->offset) >
      zstd_mf_match_gain(here->length, here->offset) + MF_LITERAL_BITS;
}

// Defined below, next to the tree it walks.
static inline size_t zstd_mf_bt_descend(zstd_match_finder_t * mf,
    const uint8_t * data, size_t pos, size_t data_size,
    zstd_mf_candidate_t * out, size_t out_cap, zstd_match_t * best_out);
static bool zstd_mf_bt_search(zstd_match_finder_t * mf, const uint8_t * data,
    size_t pos, size_t data_size, zstd_match_t * match_out);

/**
 * @brief Find best match at current position.
 *
 * @param mf Match finder context
 * @param data Input data
 * @param pos Current position
 * @param data_size Total data size
 * @param insert Whether to add @p pos to the tables as it is searched.  A
 *        position must be inserted exactly once: inserting it twice makes its
 *        chain entry point at itself, which the walk below reads as the end of
 *        the chain and so throws away every older candidate behind it.
 *        Deferred matching searches a position before the parse reaches it, so
 *        the caller tracks which positions that search has already covered.
 * @param match_out Output: best match found
 * @return true if match found, false otherwise
 */
static bool zstd_mf_find_match(zstd_match_finder_t * mf, const uint8_t * data,
    size_t pos, size_t data_size, bool insert, zstd_match_t * match_out) {
  // The tree cannot search without also inserting -- the descent is the
  // insertion -- so `insert` has no meaning for it.  Every caller passes
  // true; a caller that wanted to look without inserting would need a
  // different function, not a flag.
  if (mf->use_bt) {
    (void)insert;
    return zstd_mf_bt_search(mf, data, pos, data_size, match_out);
  }

  // Need at least MF_HASH_READ_SIZE bytes for hash function
  if (pos + MF_HASH_READ_SIZE > data_size) {
    return false;
  }

  // Hash the current position
  uint32_t hash = zstd_mf_hash4(data + pos, mf->hash_log);
  uint32_t chain_pos = mf->hash_table[hash];

  if (insert) {
    // Update hash table with current position (for future references)
    mf->hash_table[hash] = (uint32_t)(pos + 1); // +1 so 0 means "no entry"

    // Update chain table
    if (pos < mf->chain_size) {
      mf->chain_table[pos] = chain_pos;
    }
  }

  // No previous position at this hash
  if (chain_pos == 0) {
    return false;
  }
  chain_pos--; // Convert back from 1-based to 0-based

  // Search the chain for best match
  size_t best_len = MF_MIN_MATCH - 1;
  size_t best_offset = 0;
  const uint8_t * const limit = data + data_size;
  unsigned depth = mf->search_depth;

  // Everything the walk tests that does not change while it walks, worked out
  // once.  This loop is two thirds of encoding at the middle levels, and it
  // was recomputing all of this per candidate.
  //
  // How far back a sequence may reach is fixed for the whole search: the
  // window the frame header declares is a promise to the decoder about how
  // much history it must keep (RFC 8878 section 3.1.1.1.2), and a sequence
  // reaching past it is not decodable.  The chain walks strictly backwards,
  // so rather than measuring each candidate's offset against that limit, the
  // limit becomes the earliest position worth looking at.
  //
  // The test that the offset does not exceed `pos` is gone with it.  The loop
  // runs only while chain_pos < pos, so pos - chain_pos is at most pos and
  // that comparison could never have been true.
  size_t max_offset = mf->window_size;
  if (max_offset > MF_MAX_DISTANCE) {
    max_offset = MF_MAX_DISTANCE;
  }
  const size_t min_chain_pos = (pos > max_offset) ? (pos - max_offset) : 0u;

  // The first byte of the position being matched never changes.  The byte one
  // past the best match so far, and whether it is inside the buffer at all,
  // change only when the best match does -- which is rare, and is where they
  // are worked out again.
  const uint8_t cur_byte = data[pos];
  bool probe_ok = (pos + best_len < data_size);
  uint8_t probe_byte = probe_ok ? data[pos + best_len] : 0u;

  while (depth > 0 && chain_pos < pos) {
    if (chain_pos < min_chain_pos) {
      break;
    }

    // Quick check: compare first and last bytes before full comparison.
    // chain_pos < pos and pos + best_len < data_size together keep the
    // second read inside the buffer.
    if (probe_ok && data[chain_pos] == cur_byte &&
        data[chain_pos + best_len] == probe_byte) {
      // Count matching bytes
      size_t match_len =
          zstd_mf_count_match(data + pos, data + chain_pos, limit);

      if (match_len > best_len) {
        best_len = match_len;
        best_offset = pos - chain_pos;

        // A match this long is taken as it stands; see nice_length.
        if (match_len >= mf->nice_length) {
          break;
        }
        probe_ok = (pos + best_len < data_size);
        probe_byte = probe_ok ? data[pos + best_len] : 0u;
      }
    }

    // Follow chain
    if (chain_pos < mf->chain_size) {
      uint32_t next = mf->chain_table[chain_pos];
      if (next == 0 || next - 1 >= chain_pos) {
        break; // End of chain or invalid
      }
      chain_pos = next - 1;
    }
    else {
      break;
    }

    depth--;
  }

  if (best_len >= MF_MIN_MATCH && best_offset > 0) {
    match_out->offset = (uint32_t)best_offset;
    match_out->length = (uint32_t)best_len;
    return true;
  }

  return false;
}


/**
 * @brief Insert a position into the binary tree, reporting the best match
 *        met on the way down.
 *
 * WHY A TREE
 * ==========
 *
 * A hash chain is a list of earlier positions that share a hash, and finding
 * the longest match means walking it and comparing each candidate against the
 * current position from the first byte every time.  The chain is in no
 * particular order, so nothing one comparison learns helps the next, and the
 * only way to search harder is to walk further: the levels here ask for 128
 * candidates at level 7 and 2560 at level 22, and the cost is exactly that
 * number.
 *
 * The tree holds the same positions ordered by the text that follows them,
 * compared as strings.  Descending it is a binary search for the current
 * position's own suffix, so each step halves what is left rather than
 * crossing off one candidate, and the positions met on the way are the ones
 * whose text is closest to this one -- which is to say, the longest matches.
 *
 * The comparisons are not repeated either.  Coming down, every node so far
 * has sorted either before this position or after it; keep the longest match
 * with each side, and everything still below lies between those two in sorted
 * order, which means it agrees with this position for at least as many bytes
 * as the shorter of the two.  Those bytes are known to match and are not
 * looked at again.  That is what makes a step of the tree cheaper than a step
 * of the chain, rather than merely rarer.
 *
 * BUILDING IT WHILE SEARCHING IT
 * ==============================
 *
 * The descent and the insertion are one pass.  Every node passed that sorts
 * before this position belongs in the subtree of things smaller than it, and
 * every node that sorts after belongs in the larger one; writing each into
 * the slot the previous one vacated builds both subtrees as the search goes
 * down, and the search ends exactly where the new node belongs.  So a
 * position is inserted by looking for it.
 *
 * This is also why every position must be inserted exactly once and in
 * order.  Inserting one twice would make a node its own descendant.  The
 * caller does that already -- the chain wanted the same thing for a weaker
 * reason -- and positions skipped inside a match are inserted by the fill
 * loop in zstd_mf_generate_sequences().
 *
 * POSITIONS ARE ABSOLUTE
 * ======================
 *
 * The tree names positions from the start of the stream rather than from the
 * front of the caller's buffer, and indexes its slots by that number modulo a
 * power of two at least as large as the buffer.  Sliding the window is then
 * one addition to base_pos, where the chain has to walk every entry it holds
 * and rebase it.  Entries left behind by the slide sit before base_pos and
 * the walk stops at them, which prunes the tree rather than corrupting it:
 * fewer candidates, never wrong ones.
 *
 * No two positions that are live at once can share a pair of slots, because
 * that would need them to be bt_size apart and the buffer is not that wide.
 */
static inline size_t zstd_mf_bt_descend(zstd_match_finder_t * mf,
    const uint8_t * data, size_t pos, size_t data_size,
    zstd_mf_candidate_t * out, size_t out_cap, zstd_match_t * best_out) {
  // Need at least MF_HASH_READ_SIZE bytes for hash function
  if (pos + MF_HASH_READ_SIZE > data_size) {
    return 0;
  }

  const size_t cur_abs = mf->base_pos + pos;
  uint32_t hash = zstd_mf_hash4(data + pos, mf->hash_log);
  uint32_t cur = mf->hash_table[hash];
  mf->hash_table[hash] = (uint32_t)(cur_abs + 1u); // +1 so 0 means "no entry"

  // The two slots this position's own children go in, and where the next
  // node on each side gets written as the descent splits the tree.
  uint32_t * const own = &mf->bt_table[2u * (cur_abs & mf->bt_mask)];
  uint32_t * smaller = own;
  uint32_t * larger = own + 1;

  // How far back a sequence may reach, as an absolute position.  Nothing
  // before the front of the buffer can be compared against at all, whatever
  // the window allows (RFC 8878 section 3.1.1.1.2).
  const size_t max_offset = zstd_mf_max_offset(mf);
  size_t min_abs = mf->base_pos;
  if (cur_abs > max_offset && cur_abs - max_offset > min_abs) {
    min_abs = cur_abs - max_offset;
  }

  const uint8_t * const limit = data + data_size;
  size_t best_len = MF_MIN_MATCH - 1;
  size_t best_offset = 0;
  size_t found = 0;
  size_t len_smaller = 0; ///< Match with the nearest node sorting before us.
  size_t len_larger = 0;  ///< Match with the nearest node sorting after us.
  unsigned depth = mf->search_depth;

  while (depth-- > 0) {
    if (cur == 0u) {
      break;
    }
    size_t m_abs = (size_t)cur - 1u;
    if (m_abs < min_abs || m_abs >= cur_abs) {
      break; // Fallen out of the window, or not strictly earlier.
    }
    size_t m = m_abs - mf->base_pos;

    // Everything still in this subtree sorts between the two nodes already
    // met, and both of those agree with this position for at least this
    // many bytes, so this one does too.
    size_t common = (len_smaller < len_larger) ? len_smaller : len_larger;
#ifdef GCOMP_TEST_BUILD
    // The whole saving rests on that being true.  If it ever were not, the
    // length below would count bytes that do not match and the encoder would
    // emit a sequence that decodes to something else -- so the sanitizer
    // build checks it on every candidate of every block.
    assert(memcmp(data + pos, data + m, common) == 0);
#endif
    size_t len = common +
        zstd_mf_count_match(data + pos + common, data + m + common, limit);

    if (len > best_len) {
      best_len = len;
      best_offset = cur_abs - m_abs;
      // Every improvement is a match worth reporting, not just the last one.
      // They come out in increasing length order because that is the only
      // way one gets recorded, and each is the nearest source the descent
      // has found for its own length.  A caller that wants only the longest
      // passes no list, and this whole branch folds away.
      if (out && len >= MF_MIN_MATCH && found < out_cap) {
        out[found].length = (uint32_t)len;
        out[found].offset = (uint32_t)best_offset;
        found++;
      }

      // A match this long is taken as it stands; see nice_length.  The two
      // slots are closed off below, which drops whatever was still under
      // them -- a smaller tree, not a wrong one.
      if (len >= mf->nice_length) {
        break;
      }
    }

    if (pos + len >= data_size) {
      // Ran out of buffer.  Which side this position belongs on is decided
      // by bytes that are not here yet, so the descent stops rather than
      // guessing and putting the node somewhere it does not belong.
      break;
    }

    uint32_t * const child = &mf->bt_table[2u * (m_abs & mf->bt_mask)];
    if (data[pos + len] > data[m + len]) {
      // This position sorts after m, so m and everything below it on its
      // smaller side belong to this position's smaller subtree.  Carry on
      // down m's larger child, which is where anything nearer sits.
      *smaller = cur;
      smaller = child + 1;
      cur = child[1];
      len_smaller = len;
    }
    else {
      *larger = cur;
      larger = child;
      cur = child[0];
      len_larger = len;
    }
  }

  // Whatever the descent did not reach is not this position's.
  *smaller = 0u;
  *larger = 0u;

  if (out) {
    return found;
  }
  if (best_out && best_len >= MF_MIN_MATCH && best_offset > 0) {
    best_out->offset = (uint32_t)best_offset;
    best_out->length = (uint32_t)best_len;
    return 1;
  }
  return 0;
}

/**
 * @brief The descent, reporting only the longest match it met.
 */
static bool zstd_mf_bt_search(zstd_match_finder_t * mf, const uint8_t * data,
    size_t pos, size_t data_size, zstd_match_t * match_out) {
  return zstd_mf_bt_descend(mf, data, pos, data_size, NULL, 0, match_out) != 0;
}

size_t zstd_mf_find_matches(zstd_match_finder_t * mf, const uint8_t * data,
    size_t pos, size_t data_size, zstd_mf_candidate_t * out, size_t out_cap) {
  if (!mf->use_bt) {
    // The chain has no cheap way to report a frontier: its candidates arrive
    // in no useful order, so building one would mean keeping and sorting
    // every improvement.  Nothing asks -- the optimal parse is only offered
    // at tree levels -- so the one best match is what comes back.
    zstd_match_t one;
    if (out_cap == 0 ||
        !zstd_mf_find_match(mf, data, pos, data_size, true, &one)) {
      return 0;
    }
    out[0].length = one.length;
    out[0].offset = one.offset;
    return 1;
  }
  return zstd_mf_bt_descend(mf, data, pos, data_size, out, out_cap, NULL);
}

/**
 * @brief Insert position into hash table without searching.
 *
 * Used for positions we're skipping (e.g., inside a match).
 */
void zstd_mf_insert_one(zstd_match_finder_t * mf, const uint8_t * data,
    size_t pos, size_t data_size) {
  // The tree has no cheaper way in: placing a node means finding where it
  // belongs, and finding where it belongs is the search.  What the search
  // turns up is thrown away here, which is the price of keeping the tree
  // complete over the positions inside a match.
  if (mf->use_bt) {
    (void)zstd_mf_bt_descend(mf, data, pos, data_size, NULL, 0, NULL);
    return;
  }

  // Need at least MF_HASH_READ_SIZE bytes for hash function
  if (pos + MF_HASH_READ_SIZE > data_size) {
    return;
  }

  uint32_t hash = zstd_mf_hash4(data + pos, mf->hash_log);
  uint32_t prev = mf->hash_table[hash];
  mf->hash_table[hash] = (uint32_t)(pos + 1);

  if (pos < mf->chain_size) {
    mf->chain_table[pos] = prev;
  }
}

void zstd_mf_slide(zstd_match_finder_t * mf, size_t shift) {
  if (!mf || shift == 0) {
    return;
  }

  // The tree names positions from the start of the stream, so moving the
  // window changes only where data[0] sits in it.  Entries that have fallen
  // out of the buffer are behind the new base and the walk stops at them;
  // nothing has to be rewritten, which is the whole reason the tree counts
  // this way.  The chain below names positions in the buffer instead, and
  // has to move every entry it holds.
  if (mf->use_bt) {
    mf->base_pos += shift;
    return;
  }

  // Entries name positions in the window, so moving the window moves every
  // entry with it.  A position that falls off the front is dropped: the byte
  // it named is no longer there to match against.  Zero means "no entry", so
  // it is both the empty value and what a dropped entry becomes.
  for (size_t i = 0; i < mf->hash_size; i++) {
    uint32_t v = mf->hash_table[i];
    mf->hash_table[i] = (v > shift) ? (uint32_t)(v - shift) : 0u;
  }

  if (shift >= mf->chain_size) {
    memset(mf->chain_table, 0, mf->chain_size * sizeof(uint32_t));
    return;
  }
  // Moving the entries down and rebasing them are one pass, not two.  Done
  // separately -- a memmove and then a loop over what it had just written --
  // the chain table was read and written twice over, and it is the larger of
  // the two tables: a window plus a block, four bytes an entry.  Entry i of
  // the result depends only on entry i + shift of the input and i < i + shift,
  // so a forward pass reads each entry before anything overwrites it.
  size_t kept = mf->chain_size - shift;
  for (size_t i = 0; i < kept; i++) {
    uint32_t v = mf->chain_table[i + shift];
    mf->chain_table[i] = (v > shift) ? (uint32_t)(v - shift) : 0u;
  }
  memset(mf->chain_table + kept, 0, shift * sizeof(uint32_t));
}

void zstd_mf_index_range(zstd_match_finder_t * mf, const uint8_t * data,
    size_t from, size_t to, size_t data_size) {
  if (!mf || !data) {
    return;
  }
  for (size_t i = from; i < to && i + MF_HASH_READ_SIZE <= data_size; i++) {
    zstd_mf_insert_one(mf, data, i, data_size);
  }
}

//
// Sequence Generation
//

/**
 * @brief Generate sequences from input data using match finder.
 *
 * @param mf Match finder context
 * @param data Window contents: history followed by the block to encode
 * @param data_size Total bytes in @p data
 * @param start_pos First position to encode; everything before it is history
 *        that the caller has already indexed
 * @param sequences Output sequence array
 * @param max_sequences Maximum sequences to generate
 * @param num_sequences_out Output: number of sequences generated
 * @param literals_out Output: literals buffer (caller provides)
 * @param literals_size_out Output: total literals size
 * @return GCOMP_OK on success
 */
gcomp_status_t zstd_mf_generate_sequences(zstd_match_finder_t * mf,
    const uint8_t * data, size_t data_size, size_t start_pos,
    zstd_sequence_t * sequences, size_t max_sequences,
    size_t * num_sequences_out, uint8_t * literals_out,
    size_t * literals_size_out, uint32_t * rep_offset_1,
    uint32_t * rep_offset_2, uint32_t * rep_offset_3) {
  if (!mf || !data || !sequences || !num_sequences_out || !literals_out ||
      !literals_size_out) {
    return GCOMP_ERR_INVALID_ARG;
  }

  // The tables are not reset here and the history before start_pos is not
  // re-indexed.  Both belong to the caller: a stream's blocks share one
  // window, so each block's history is the previous blocks, already indexed
  // as they were encoded.  Resetting here made every block start from nothing
  // - no match could cross a block boundary, and on a multi-megabyte file
  // that threw the history away 128 KB at a time.
  size_t pos = start_pos;
  size_t lit_start = start_pos;
  size_t num_seq = 0;
  size_t lit_pos = 0;

  uint32_t rep1 = rep_offset_1 ? *rep_offset_1 : ZSTD_REP_OFFSET_1_INIT;
  uint32_t rep2 = rep_offset_2 ? *rep_offset_2 : ZSTD_REP_OFFSET_2_INIT;
  uint32_t rep3 = rep_offset_3 ? *rep_offset_3 : ZSTD_REP_OFFSET_3_INIT;

  while (pos < data_size && num_seq < max_sequences) {
    zstd_match_t match;

    // Try to find a match
    if (zstd_mf_find_match(mf, data, pos, data_size, true, &match)) {
      // Deferred matching: a match here blocks every match that starts inside
      // it, so before committing, look one byte on and keep whichever is
      // worth more.  `indexed` is the highest position these look-ahead
      // searches have put into the tables; the fill loop below must not
      // insert those a second time.
      size_t indexed = pos;
      unsigned deferrals = mf->lazy_depth;
      while (deferrals > 0 && match.length < mf->nice_length &&
          pos + 1 < data_size) {
        zstd_match_t later;
        bool found =
            zstd_mf_find_match(mf, data, pos + 1, data_size, true, &later);
        indexed = pos + 1;
        if (!found || !zstd_mf_prefer_later(&later, &match)) {
          break;
        }
        // Give up the match here; this byte becomes one more literal.
        pos++;
        match = later;
        deferrals--;
      }

      // Convert to encoded offset (zstd uses codes 1-3 for repeat offsets)
      // Note: When lit_length == 0, offset encoding is different:
      //   offset 1 -> rep_offset_2
      //   offset 2 -> rep_offset_3
      //   offset 3 -> rep_offset_1 - 1
      // To avoid this complexity, we use new offset encoding when lit_length==0
      // and the match is a repeat offset.
      uint32_t encoded_offset = match.offset;
      size_t lit_len = pos - lit_start;

      if (lit_len > 0) {
        // Normal case: lit_length > 0
        if (match.offset == rep1) {
          encoded_offset = 1;
          // rep1 stays the same
        }
        else if (match.offset == rep2) {
          encoded_offset = 2;
          // Swap rep1 and rep2
          uint32_t tmp = rep2;
          rep2 = rep1;
          rep1 = tmp;
        }
        else if (match.offset == rep3) {
          encoded_offset = 3;
          // Rotate offsets
          uint32_t tmp = rep3;
          rep3 = rep2;
          rep2 = rep1;
          rep1 = tmp;
        }
        else {
          // New offset: add 3 (offset codes 1-3 are for repeat offsets)
          encoded_offset = match.offset + 3;
          // Update repeat offsets
          rep3 = rep2;
          rep2 = rep1;
          rep1 = match.offset;
        }
      }
      else {
        // Special case: lit_length == 0
        // When lit_length is 0, repeat offset codes are shifted:
        //   offset 1 -> rep_offset_2
        //   offset 2 -> rep_offset_3
        //   offset 3 -> rep_offset_1 - 1
        // For simplicity, we always encode as new offset to avoid this
        // complexity. This is less efficient but correct.
        encoded_offset = match.offset + 3;
        rep3 = rep2;
        rep2 = rep1;
        rep1 = match.offset;
      }

      // Copy literals before this match (lit_len computed above)
      memcpy(literals_out + lit_pos, data + lit_start, lit_len);
      lit_pos += lit_len;

      // Record sequence
      sequences[num_seq].lit_length = (uint32_t)lit_len;
      sequences[num_seq].match_offset = encoded_offset;
      sequences[num_seq].match_length = match.length;
      num_seq++;

      // Advance position
      // Insert intermediate positions into hash table for better chaining,
      // skipping any the deferral search above already inserted.
      size_t match_end = pos + match.length;
      size_t fill_from = (indexed > pos) ? indexed + 1 : pos + 1;
      for (size_t i = fill_from;
           i < match_end && i + MF_HASH_READ_SIZE <= data_size; i++) {
        zstd_mf_insert_one(mf, data, i, data_size);
      }

      pos = match_end;
      lit_start = pos;
    }
    else {
      // No match found, advance by one
      pos++;
    }
  }

  // Copy remaining literals
  if (lit_start < data_size) {
    size_t remaining = data_size - lit_start;
    memcpy(literals_out + lit_pos, data + lit_start, remaining);
    lit_pos += remaining;
  }

  *num_sequences_out = num_seq;
  *literals_size_out = lit_pos;

  // Update repeat offsets
  if (rep_offset_1)
    *rep_offset_1 = rep1;
  if (rep_offset_2)
    *rep_offset_2 = rep2;
  if (rep_offset_3)
    *rep_offset_3 = rep3;

  return GCOMP_OK;
}
